# Generated by Django 5.0.7 on 2024-08-02 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIKeys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikeys',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 14, 24, 7, 209542)),
        ),
    ]
