# Generated by Django 5.0.7 on 2024-08-02 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MaxValueValidator(10)])),
                ('description', models.TextField()),
                ('imageUrl', models.ImageField(blank=True, upload_to='')),
                ('movieUrl', models.URLField(blank=True)),
            ],
        ),
    ]
