# Generated by Django 5.0.7 on 2024-08-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='imageUrl',
            field=models.TextField(blank=True),
        ),
    ]
